services:
  testapi:
    build: .
    ports:
      - 8080:8080
      - 8081:8081
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./Prometheus:/etc/prometheus
      - ./Prometheus/data:/prometheus
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000