global:
  scrape_interval: 15s

# A list of scrape configurations.
scrape_configs:
- job_name: prometheus
  static_configs: 
  - targets:
    - localhost:9090

- job_name: testapi
  static_configs: 
  - targets:
    - testapi:8080

